Controllers/ClassementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProblemSolvingPlatform.Models;

namespace ProblemSolvingPlatform.Controllers
{
    public class ClassementsController : Controller
    {
        private readonly ProblemSolvingPlatformContext _context;

        public ClassementsController(ProblemSolvingPlatformContext context)
        {
            _context = context;
        }

        // GET: Classements
        public async Task<IActionResult> Index()
        {
            var problemSolvingPlatformContext = _context.Classements.Include(c => c.User);
            return View(await problemSolvingPlatformContext.ToListAsync());
        }

        // GET: Classements/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var classement = await _context.Classements
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.ClassementId == id);
            if (classement == null)
            {
                return NotFound();
            }

            return View(classement);
        }

        // GET: Classements/Create
        public IActionResult Create()
        {
            // Use Identity user key 'Id' and display 'UserName' instead of non-existing 'UserId'
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "UserName");
            return View();
        }

        // POST: Classements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClassementId,UserId,Score,Rang")] Classement classement)
        {
            if (ModelState.IsValid)
            {
                _context.Add(classement);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "UserName", classement.UserId);
            return View(classement);
        }

        // GET: Classements/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var classement = await _context.Classements.FindAsync(id);
            if (classement == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "UserName", classement.UserId);
            return View(classement);
        }

        // POST: Classements/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClassementId,UserId,Score,Rang")] Classement classement)
        {
            if (id != classement.ClassementId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(classement);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClassementExists(classement.ClassementId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "UserName", classement.UserId);
            return View(classement);
        }

        // GET: Classements/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var classement = await _context.Classements
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.ClassementId == id);
            if (classement == null)
            {
                return NotFound();
            }

            return View(classement);
        }

        // POST: Classements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var classement = await _context.Classements.FindAsync(id);
            if (classement != null)
            {
                _context.Classements.Remove(classement);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClassementExists(int id)
        {
            return _context.Classements.Any(e => e.ClassementId == id);
        }
    }
}

Controllers/ProblemesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProblemSolvingPlatform.Models;
using ProblemSolvingPlatform.Services;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Identity;

namespace ProblemSolvingPlatform.Controllers
{
    public class ProblemesController : Controller
    {
        private readonly ProblemSolvingPlatformContext _context;
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly PistonCodeExecutionService _pistonService;
        private readonly UserManager<User> _userManager;

        public ProblemesController(
            ProblemSolvingPlatformContext context,
            IHttpClientFactory httpClientFactory,
            PistonCodeExecutionService pistonService,
            UserManager<User> userManager)
        {
            _context = context;
            _httpClientFactory = httpClientFactory;
            _pistonService = pistonService;
            _userManager = userManager;
        }

        // GET: Problemes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Problemes.ToListAsync());
        }

        // GET: Problemes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var probleme = await _context.Problemes
                .FirstOrDefaultAsync(m => m.ProbId == id);
            if (probleme == null)
            {
                return NotFound();
            }

            // Load comments for this problem
            var comments = await _context.Commentaires
                .Include(c => c.User)
                .Where(c => c.Probleme == id.ToString())
                .OrderByDescending(c => c.DateCreation)
                .ToListAsync();
            
            ViewBag.Comments = comments;

            return View(probleme);
        }

        // GET: Problemes/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Problemes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Title,Descr,Difficulte,Language,FunctionTemplate,TestCases")] Probleme probleme)
        {
            if (ModelState.IsValid)
            {
                _context.Add(probleme);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(probleme);
        }

        // GET: Problemes/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var probleme = await _context.Problemes.FindAsync(id);
            if (probleme == null)
            {
                return NotFound();
            }
            return View(probleme);
        }

        // POST: Problemes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("ProbId,Title,Descr,Difficulte,Language,FunctionTemplate,TestCases")] Probleme probleme)
        {
            if (id != probleme.ProbId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(probleme);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProblemeExists(probleme.ProbId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(probleme);
        }

        // GET: Problemes/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var probleme = await _context.Problemes
                .FirstOrDefaultAsync(m => m.ProbId == id);
            if (probleme == null)
            {
                return NotFound();
            }

            return View(probleme);
        }

        // POST: Problemes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var probleme = await _context.Problemes.FindAsync(id);
            if (probleme != null)
            {
                _context.Problemes.Remove(probleme);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // POST: Problemes/ExecuteCode
        [HttpPost]
        public async Task<IActionResult> ExecuteCode([FromBody] CodeExecutionRequest request)
        {
            try
            {
                var client = _httpClientFactory.CreateClient();

                // Set timeout to prevent hanging
                client.Timeout = TimeSpan.FromSeconds(10);

                // Map language names to OneCompiler language codes
                var languageMap = new Dictionary<string, string>
                {
                    { "javascript", "javascript" },
                    { "python", "python3" },
                    { "python3", "python3" },
                    { "java", "java" },
                    { "cpp", "cpp" },
                    { "c++", "cpp" },
                    { "csharp", "csharp" },
                    { "c#", "csharp" },
                    { "go", "go" },
                    { "rust", "rust" },
                    { "php", "php" },
                    { "ruby", "ruby" },
                    { "typescript", "typescript" }
                };

                var language = languageMap.ContainsKey(request.Language?.ToLower() ?? "")
                    ? languageMap[request.Language.ToLower()]
                    : "python3";

                var payload = new OneCompilerPayload
                {
                    Language = language,
                    Code = request.Code,
                    Stdin = request.Input ?? ""
                };

                var content = new StringContent(
                    System.Text.Json.JsonSerializer.Serialize(payload),
                    System.Text.Encoding.UTF8,
                    "application/json");

                try
                {
                    var response = await client.PostAsync("https://api.onecompiler.com/api/v1/code/exec", content);

                    if (response.IsSuccessStatusCode)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        return Ok(result);
                    }
                    else
                    {
                        return BadRequest(new { error = "Failed to execute code", status = response.StatusCode });
                    }
                }
                catch (HttpRequestException hre) when (hre.InnerException is System.Net.Sockets.SocketException)
                {
                    return BadRequest(new
                    {
                        error = "Network error: Cannot connect to OneCompiler API. Check your internet connection or firewall settings.",
                        details = hre.Message
                    });
                }
                catch (TaskCanceledException)
                {
                    return BadRequest(new { error = "Request timeout: Code execution took too long (>10 seconds)" });
                }
            }
            catch (Exception ex)
            {
                return BadRequest(new { error = "An error occurred: " + ex.Message, type = ex.GetType().Name });
            }
        }

        // GET: Problemes/GetPistonRuntimes
        [HttpGet]
        public async Task<IActionResult> GetPistonRuntimes()
        {
            try
            {
                var runtimes = await _pistonService.GetRuntimesAsync();
                return Ok(runtimes);
            }
            catch (Exception ex)
            {
                return BadRequest(new { error = "Failed to fetch runtimes", details = ex.Message });
            }
        }

        // POST: Problemes/ExecuteCodeWithPiston
        [HttpPost]
        public async Task<IActionResult> ExecuteCodeWithPiston([FromBody] PistonCodeRequest request)
        {
            try
            {
                var languageMap = new Dictionary<string, string>
                {
                    { "javascript", "javascript" },
                    { "js", "javascript" },
                    { "python", "python" },
                    { "python3", "python" },
                    { "py", "python" },
                    { "java", "java" },
                    { "cpp", "c++" },
                    { "c++", "c++" },
                    { "csharp", "csharp" },
                    { "c#", "csharp" },
                    { "cs", "csharp" },
                    { "go", "go" },
                    { "rust", "rust" },
                    { "php", "php" },
                    { "ruby", "ruby" },
                    { "typescript", "typescript" },
                    { "ts", "typescript" }
                };

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ProblemSolvingPlatform.Models.User> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title class="text-white">@ViewData["Title"] - ProblemSolvingPlatform</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">


    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProblemSolvingPlatform.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Inter', sans-serif;
            background-color: #0a0a0a !important;
        }
        .navbar-glass {
            background: rgba(10, 10, 10, 0.8) !important;
            backdrop-filter: blur(10px);
            -webkit-backdrop-filter: blur(10px);
            border-bottom: 1px solid rgba(255, 255, 255, 0.1) !important;
        }
        .nav-link {
            font-weight: 500;
            transition: color 0.2s ease;
        }
        .nav-link:hover {
            color: #6366f1 !important;
        }
        .btn-logout {
            background: rgba(220, 38, 38, 0.1);
            color: #ef4444 !important;
            border: 1px solid rgba(220, 38, 38, 0.2);
            padding: 0.4rem 1rem;
            border-radius: 0.5rem;
            transition: all 0.2s;
        }
        .btn-logout:hover {
            background: rgba(220, 38, 38, 0.2);
            border-color: rgba(220, 38, 38, 0.4);
        }
        footer {
            background: #0a0a0a;
            border-top: 1px solid rgba(255, 255, 255, 0.1) !important;
        }
    </style>
</head>
<body class="bg-black text-white">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark sticky-top navbar-glass mb-4 shadow-sm" style="top: 0; z-index: 1030;">
            <div class="container">
                <a class="navbar-brand fw-bold d-flex align-items-center" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="bi bi-cpu-fill me-2 text-primary"></i>
                    <span>Code<span class="text-primary">master</span></span>
                </a>
                <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 align-items-center">
                        <li class="nav-item">
                            <a class="nav-link text-white px-3" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white px-3" asp-area="" asp-controller="Problemes" asp-action="Index">Problems</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white px-3" asp-area="" asp-controller="Classements" asp-action="Index">Leaderboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white px-3 opacity-75" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav align-items-center gap-2">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle d-flex align-items-center p-0" href="#" id="profileDropdown" role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                    <div class="position-relative">
                                        @{
                                            var user = await UserManager.GetUserAsync(User);
                                            var profilePic = user?.ProfilePicture ?? "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png";
                                        }
                                        <img src="@profilePic"
                                             class="rounded-circle border border-2 border-primary" width="38" height="38" alt="Profile" style="object-fit: cover;">
                                        <span class="position-absolute bottom-0 end-0 p-1 bg-success border border-light rounded-circle"></span>
                                    </div>
                                </a>

                                <ul class="dropdown-menu dropdown-menu-end shadow-lg border-secondary bg-dark" aria-labelledby="profileDropdown">
                                    <li class="px-3 py-2 border-bottom border-secondary mb-2">
                                        <span class="d-block text-white small">Signed in as</span>
                                        <strong class="text-white">@User.Identity.Name</strong>
                                    </li>
                                    <li>
                                        <a class="dropdown-item text-white py-2" asp-area="Identity" asp-page="/Account/Profile">
                                            <i class="bi bi-person me-2"></i> My Profile
                                        </a>
                                    </li>

                                    <li>
                                        <a class="dropdown-item text-white py-2" asp-area="Identity" asp-page="/Account/EditProfile">
                                            <i class="bi bi-gear me-2"></i> Settings
                                        </a>
                                    </li>

                                    <li><hr class="dropdown-divider border-secondary"></li>

                                    <li class="px-2">
                                        <form method="post" asp-area="Identity" asp-page="/Account/Logout">
                                            <button class="btn btn-danger w-100 py-2 btn-sm rounded-pill">
                                                <i class="bi bi-box-arrow-right me-1"></i> Logout
                                            </button>
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="btn btn-outline-light rounded-pill px-4 me-2" asp-area="Identity" asp-page="/Account/Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-primary rounded-pill px-4" asp-area="Identity" asp-page="/Account/Register">Sign Up</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" >
        @RenderBody()
    </main>

    <footer class="footer text-white-50 py-4 mt-auto">
        <div class="container text-center text-md-start">
            <div class="row align-items-center">
                <div class="col-md-6">
                    <span>&copy; 2025 - <span class="text-white">CodeMaster</span></span>
                    <span class="mx-2">|</span>
                    <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-white-50 text-decoration-none hover-white">Privacy Policy</a>
                </div>
                <div class="col-md-6 text-md-end mt-3 mt-md-0">
                    <a href="#" class="text-white-50 fs-5 mx-2"><i class="bi bi-github"></i></a>
                    <a href="#" class="text-white-50 fs-5 mx-2"><i class="bi bi-twitter-x"></i></a>
                    <a href="#" class="text-white-50 fs-5 mx-2"><i class="bi bi-linkedin"></i></a>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>